### ISSUE TITLE
No support to connect a Unix socket

### ISSUE THREAD

**Issue by Jean-Daniel** [kumina/unbound_exporter#8]
One way to secure the connection to unbound remote-control is to use unix socket with the right permissions. 

When using this method, it is easy to limit the scope of the remote-control socket. Moreover Unix socket perform better than TCP sockets and requires less CPU.

On the unbound side, the config look like this:
```
remote-control:
    control-enable: yes
    control-use-cert: no
    control-interface: /var/run/unbound.sock
```

Unfortunately, the unbound_exporter requires a TCP connection.
